### ISSUE TITLE
precise_ephemerides.py cannot be imported

### ISSUE THREAD

**Issue by plutonheaven** [Stanford-NavLab/gnss_lib_py#88]
**Describe the bug**
`from gnss_lib_py.parsers.precise_ephemerides import parse_sp3` returns a `ModuleNotFoundError`

**To Reproduce**
Type the line of the bug description in a python console.
I use PyCharm and they suggest (through auto-completion) the 3 other files present in "gnss_lib_py/parsers", ie "ephemeris", "android" and "navdata", but not this "precise_ephemerides"

**System Information (please complete the following information):**
- OS: Ubuntu 20.04 and Windows 10
- Python Version: 3.10.8
-  gnss_lib_py: 0.1.7, installed using `pip install gnss-lib-py`

**Comment by betaBison** [comment]
Hi @plutonheaven. This is because the `0.1.7` version of `gnss_lib_py` did not yet include `precise_ephemerides`. This will be resolved as soon as #87 is merged which releases the `0.1.8` version of `gnss_lib_py` to pypi. That merge should happen in the next day or two.

They're a bit more work, but if you need that functionality immediately you can check out either the [Editable Installation](https://gnss-lib-py.readthedocs.io/en/latest/install.html#editable-installation) steps or the [Developer Installation](https://gnss-lib-py.readthedocs.io/en/latest/install.html#developer-installation) steps which should resolve your issue by using the latest version of the `main` branch on GitHub rather than the `0.1.7` release.

**Comment by plutonheaven** [comment]
Thanks for the quick answer! I'm reassured that I was not missing something... Will wait for `0.1.8`!!

**Comment by betaBison** [comment]
@plutonheaven The `0.1.8` release of gnss_lib_py is now public. Sorry, that took longer than I expected. If you haven't already seen it, the tutorial for processing precise ephemerides is on our documentation website [here](https://gnss-lib-py.readthedocs.io/en/latest/tutorials/tutorials_parsers_notebook.html#Precise-Ephemerides-Processing).

More importantly, many thanks for bringing to our attention the inconsistency between our documentation and the current pypi release. We'll be changing our workflow to maintain consistency between our public documentation and current release in the future.

Please let us know if you have other issues or questions in the future. Cheers!
